# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad3da0cc45b4a9d471fa0eea5d85f4348ff010b96311e6bc74f1fb0fd5a316fb77fb3a0475d9932555833200c543babc2b820d3b4c5bda3f6ac923ab59bd014

test:
  secret_key_base: 243a6c35269bcf75c3086d8d6efab8fe2e9b1efe2f83055877c1f2e059b0ea3d0ea9d9d7a82b1966f2efb737929a9070dbf271d77b8bd6359311c1d6589af721

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
